export const ext = Symbol('ext');
export const cst = Symbol('cst');
export const unk = Symbol('unk');
export const any = Symbol('any');
export const num = Symbol('num');
export const str = Symbol('str');
export const bol = Symbol('bol');
export const res = Symbol('res');
export const rec = Symbol('rec');
export const cnj = Symbol('cnj');
export const dsj = Symbol('dsj');
export const app = Symbol('app');
export const abs = Symbol('abs');
export const ref = Symbol('ref');
export const sav = Symbol('sav');
export const aka = Symbol('aka');
export const iov = Symbol('iov');
export const lit = Symbol('lit');
export const acs = Symbol('acs');
export const mod = Symbol('mod');
export const blt = Symbol('blt');
export const visit_graph = o => e => (f => () => f(e))(o[e.kind]);
export const visit_type = o => e => (f => () => f(e))(o[e.kind]);
export const typ_new = (() => {
    let n = 0;
    return () => (typ_ref(`__${n++}`));
})();
export const typ_num = () => ({ kind: num });
export const typ_str = () => ({ kind: str });
export const typ_bol = () => ({ kind: bol });
export const typ_unk = () => ({ kind: unk });
export const typ_any = () => ({ kind: any });
export const typ_lit = value => ({ kind: lit, value });
export const typ_rec = elements => ({ kind: rec, elements });
export const typ_ref = name => ({ kind: ref, name });
export const typ_ext = operand => ({ kind: ext, operand });
export const typ_iov = operand => ({ kind: iov, operand });
export const typ_aka = (name, identity) => ({ kind: aka, name, identity });
export const typ_abs = (vars, lhs, rhs) => ({ kind: abs, vars, lhs, rhs });
export const typ_cnj = (lhs, rhs) => ({ kind: cnj, lhs, rhs });
export const typ_dsj = (lhs, rhs) => ({ kind: dsj, lhs, rhs });
export const term_lit = value => ({ kind: lit, value });
export const term_ref = (location, name) => ({ kind: ref, location, name });
export const term_mod = (module, body) => ({ kind: mod, module, body });
export const term_cst = (location, destination, body) => ({ kind: cst, location, destination, body });
export const term_res = elements => ({ kind: res, elements });
export const term_rec = elements => ({ kind: rec, elements });
export const term_acs = (location, lhs, rhs) => ({ kind: acs, location, lhs, rhs });
export const term_app = (location, lhs, rhs) => ({ kind: app, location, lhs, rhs });
export const term_abs = (location, parameter, body) => ({ kind: abs, location, parameter, body });
export const term_blt = code => ({ kind: blt, code });
export const term_ext = value => ({ kind: ext, value });
export const term_iov = (iokind, operands) => ({ kind: iov, iokind, operands });
export const term_aka = (identity, name) => ({ kind: aka, name, identity });
export const term_sav = (record, body) => ({ kind: sav, record, body });
//# sourceMappingURL=graph.js.map